DATA_PATH: "./data"
OUTPUT_PATH: "./outputs"
PROJECT: "Pokemon"

model:
  base_learning_rate: 4.5e-6
  target: leonardo_da_vqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: leonardo_da_vqgan.loss.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        disc_num_layers: 2
        codebook_weight: 1.0

data:
  target: leonardo_da_vqgan.data.datasets.pokemon.Pokemon
  params:
    batch_size: 24
    num_workers: 12
    max_epoch: 10
    train:
      target: leonardo_da_vqgan.data.datasets.pokemon.PokemonDataset
      params:
        root: ./data 
        train: True
    validation:
      target: leonardo_da_vqgan.data.datasets.pokemon.PokemonDataset
      params:
        root: ./data 
        train: False
    test:
      target: leonardo_da_vqgan.data.datasets.pokemon.PokemonDataset
      params:
        root: ./data 
        train: False
